### ISSUE TITLE
Error attempting first example

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/CFA-Python#2]
So this is with python 3.9.13 on a Mac having compiled CFA-C with gcc
```
 gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I got two warnings with that, then followed the Python instructions (with a pip install a la #1), and then got this:
```
python tests/examples/example1.py
Example 1 save
----------------
Exception ignored in: <function CFADataset.__del__ at 0x7fa26025c820>
Traceback (most recent call last):
  File "/Users/BNL28/miniconda3/envs/pymb22a/lib/python3.9/site-packages/CFAPython/CFADataset.py", line 54, in __del__
    raise CFAException(cfa_err)
CFAPython.CFAExceptions.CFAException: 13
Example 1 load
Traceback (most recent call last):
  File "/Users/BNL28/GitRepos/CFA/CFA-Python/tests/examples/example1.py", line 97, in <module>
    example1_load()
  File "/Users/BNL28/GitRepos/CFA/CFA-Python/tests/examples/example1.py", line 46, in example1_load
    cfa = CFADataset(example1_path, CFAFileFormat.CFANetCDF, "r")
  File "/Users/BNL28/miniconda3/envs/pymb22a/lib/python3.9/site-packages/CFAPython/CFADataset.py", line 44, in __init__
    raise CFAException(cfa_err)
CFAPython.CFAExceptions.CFAException: 2
Exception ignored in: <function CFADataset.__del__ at 0x7fa26025c820>
Traceback (most recent call last):
  File "/Users/BNL28/miniconda3/envs/pymb22a/lib/python3.9/site-packages/CFAPython/CFADataset.py", line 57, in __del__
    raise CFAException(cfa_err)
CFAPython.CFAExceptions.CFAException: -510
```

I have no idea where to go with this!

**Comment by bnlawrence** [comment]
I understand that there is a missing directory (` mkdir examples/test`) after which the example runs. Install and/or docs need updating before closing this ticket. I've made a another ticket for the cryptic error messages (#3)
